Labs: GitHub-177: Add functionality to define constant to enable nginx logging
rtCamp/nginx-helper pull request #316
Opened 2024-01-12 07:08 UTC by vishalkakadiya

As discussed over the call on the **11th of January**:
- Adds functionality to define the **ENABLE_NGINX_HELPER_LOGS** constant in the wp-config file to enable the logging feature.
- Users who are already using the nginx-helper plugin with **Enable Logging** will not be affected, but if they disable the logging then they need to define the **ENABLE_NGINX_HELPER_LOGS** constant to enable the logging feature again.

**Ref:** https://github.com/rtCamp/labs/issues/177

2024-01-12 07:20 UTC, gagan0123 requested changes

2024-01-12 07:50 UTC, vishalkakadiya commented on admin/partials/nginx-helper-general-options.php
> +								);
Done

2024-01-12 10:29 UTC, vishalkakadiya commented on admin/partials/nginx-helper-general-options.php
> +								<?php echo esc_attr( $is_checkbox_enabled ? '' : ' disabled ' ); ?>
@gagan0123 This is fixed now. Thanks!

2024-01-12 11:36 UTC, gagan0123 commented on admin/partials/nginx-helper-general-options.php
> +								<?php echo esc_attr( $is_checkbox_enabled ? '' : ' disabled ' ); ?>
Thanks :)

2024-01-12 12:09 UTC, gagan0123 requested changes

2024-01-12 12:09 UTC, gagan0123 commented on admin/partials/nginx-helper-general-options.php
> +									'<pre>[<b>NOTE:</b> %1$s<br /><b>define( \'NGINX_HELPER_LOG\', true )</b> %2$s <b>wp-config.php</b>]</pre>',
```suggestion
									'<pre>[<b>NOTE:</b> %1$s<br /><b> define( \'NGINX_HELPER_LOG\', true )</b> %2$s <b>wp-config.php</b>]</pre>',
```

2024-01-12 12:09 UTC, gagan0123 commented on tests/e2e-playwright/specs/04_enable-debug-option-test.spec.js
> +      "[NOTE: To activate the logging feature, you must define the constantdefine( 'NGINX_HELPER_LOG', true ) in your wp-config.php]"
```suggestion
      "[NOTE: To activate the logging feature, you must define the constant define( 'NGINX_HELPER_LOG', true ) in your wp-config.php]"
```

2024-01-12 12:32 UTC, vishalkakadiya commented on admin/partials/nginx-helper-general-options.php
> +									'<pre>[<b>NOTE:</b> %1$s<br /><b>define( \'NGINX_HELPER_LOG\', true )</b> %2$s <b>wp-config.php</b>]</pre>',
@gagan0123 fixed this now, thanks!

2024-01-12 12:32 UTC, vishalkakadiya commented on tests/e2e-playwright/specs/04_enable-debug-option-test.spec.js
> +      "[NOTE: To activate the logging feature, you must define the constantdefine( 'NGINX_HELPER_LOG', true ) in your wp-config.php]"
@gagan0123 fixed this now, thanks!

2024-01-17 05:05 UTC, gagan0123 approved these changes

2024-01-17 05:14 UTC, merged