Adds Default options in wp_options table to allow manipulating options from WP CLI.
rtCamp/nginx-helper pull request #354
Opened 2024-09-19 06:48 UTC by Vedant-Gandhi

## Description
The aim of this PR is to add support for purging AMP URL's.

## Type
- New Feature

## Reference Issue
- https://github.com/rtCamp/nginx-helper/issues/307

## Testing
The code has been tested locally and is working as expected.

2024-09-24 22:03 UTC, SH4LIN requested changes

2024-09-24 22:03 UTC, SH4LIN commented on admin/class-nginx-helper-admin.php
> +        $removable_default_settings = array(
Why are we removing these settings from the list of settings to be stored in the options table?

2024-09-27 09:53 UTC, SH4LIN commented on admin/class-nginx-helper-admin.php
> +        $diffed_options = wp_parse_args( $default_settings, $options );
According to the documentation and function signature, keep the default options as the second argument and the options (`$args`) as the first.

2024-09-30 07:26 UTC, SH4LIN approved these changes
LGTM!

2024-09-30 07:31 UTC, Vedant-Gandhi commented
@SH4LIN The action is throwing an error because it is utilising a deprecated version of the upload artifact API.

2024-10-23 06:41 UTC, merged