[v2.3.0] Bump Plugin Version and Update Readme Files
rtCamp/nginx-helper pull request #373
Opened 2024-12-19 06:17 UTC by Vedant-Gandhi

## Description

### Changes 
- Updated the Plugin Version to 2.3.0
- Updated the po and mo files.
- Updated Readme files reflecting the changelog and plugin version.

2024-12-19 14:19 UTC, Pathan-Amaankhan requested changes

2024-12-19 14:19 UTC, Pathan-Amaankhan commented on readme.txt
Update the `Stable tag` also to the latest version i.e. `2.3.0` in this file.

2024-12-19 14:19 UTC, Pathan-Amaankhan commented on README.md
Update the Stable tag also to the latest version i.e. `2.3.0` in this file.

2024-12-19 16:46 UTC, Pathan-Amaankhan requested changes

2024-12-19 16:46 UTC, Pathan-Amaankhan commented on readme.txt
>  Tested up to: 6.1
Missed updating Tested up to. Please makesure that fields in readme.md and readme.txt are similar.

2024-12-19 19:16 UTC, Pathan-Amaankhan approved these changes
LGTM

2024-12-19 19:17 UTC, Pathan-Amaankhan requested changes
Please raise a develop PR first before merging to master.
We will first test the changes on develop.

Next, if we have already merged the fixes/features on master, we can directly raise a version bump PR for master.

If the changes are not merged, then a master <-> develop sync PR should be raised to migrate the develop commits to master after testing develop. (ref PR: https://github.com/rtCamp/nginx-helper/pull/318)

2024-12-20 10:22 UTC, Pathan-Amaankhan commented on README.md
> +**Q. Can I override the redis socket path, username, password?**
Have we added this on develop?
If no than please raise a PR that adds the same on develop...

2024-12-20 10:23 UTC, Vedant-Gandhi commented on README.md
> +**Q. Can I override the redis socket path, username, password?**
Okay will add it.

2024-12-20 10:33 UTC, Vedant-Gandhi commented on README.md
> +**Q. Can I override the redis socket path, username, password?**
Ref - https://github.com/rtCamp/nginx-helper/pull/375

2024-12-20 12:42 UTC, Pathan-Amaankhan approved these changes

2024-12-23 06:57 UTC, merged